<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHh57xjv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHh57xjv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHh57xjv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHh57xjv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHh57xjv\App_KernelDevDebugContainer([
    'container.build_hash' => 'Hh57xjv',
    'container.build_id' => '2a6e2214',
    'container.build_time' => 1589404306,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHh57xjv');
